[general]
import = [ "~/.config/alacritty/colors.toml" ]

[window]
padding = {x = 14, y = 14}
dynamic_padding = true

[font]
size = 14.0
normal = { family = "Caskaydia Cove Nerd Font" }
builtin_box_drawing = false
