add_newline = true

format = """
[╭── ](white)\
$jobs\
$directory\
$git_branch\
$git_status\
$nix_shell\
\n[╰─](white)\
$character
"""

[jobs]
style = "bold red"

[directory]
truncation_length = 4
truncation_symbol = "../"
style = "bold blue"

[git_branch]
style = "white"

[git_status]
style = "bold purple"

[nix_shell]
symbol = "󱄅 "
style = "blue"
format = "[$symbol]($style) "

[character]
success_symbol = "[❯](white)"
error_symbol = "[❯](white)"
