add_newline = true

format = """
[╭── ](bold #888888)\
$jobs\
$directory\
$git_branch\
$git_status\
$nix_shell\
\n[╰─](bold #888888)\
$character
"""

[jobs]
style = "bold red"

[directory]
truncation_length = 3
truncation_symbol = "../"
style = "white"

[git_branch]
symbol = " "
style = "white"
format = '[on ](#888888)[$symbol$branch]($style) '

[git_status]
disabled = true
style = "#888888"

[nix_shell]
symbol = "󱄅 "
style = "white"
format = '[via ](#888888)[$symbol$name]($style) '

[character]
success_symbol = "[λ](bold blue)"
error_symbol = "[λ](bold red)"
