add_newline = true

format = """
[╭── ](white)\
$directory\
$git_branch\
$git_status
[╰─](white)\
$character
"""

[directory]
truncation_length = 3
truncation_symbol = "../"

[git_branch]
style = "bold white"

[git_status]
style = "bold purple"

[character]
success_symbol = "[❯](white)"
error_symbol = "[❯](white)"
